# Input data
name = input("Enter your name: ")
date = input("Enter the date: ")
print()
CO2homeam = input("CO2 reading home (AM)? ")
com1 = input("Comment for reading: ")
print()
CO2portam = input("CO2 reading transportation (AM)? ")
com2 = input("Comment for reading: ")
print()
CO2workam = input("CO2 reading work (AM)? ")
com3 = input("Comment for reading: ")
print()
CO2workpm = input("CO2 reading work (PM)? ")
com4 = input("Comment for reading: ")
print()
CO2portpm = input("CO2 reading transportation (PM)? ")
com5 = input("Comment for reading: ")
print()
CO2homepm = input("CO2 reading home (PM)? ")
com6 = input("Comment for reading: ")
print()

# Output
print("Student name:\t",name)
print("Date \t", date)
print()
print("-->\tC a r b o n \tD i o x i d e \tR e a d i n g s  <-- ")
print()
print("Location\tTime\tLevel\tDescription")
print("--------\t----\t-----\t-----------")
print("Home\t\tAM\t"+CO2homeam+"\t"+com1)
print("Transport\tAM\t"+CO2portpm+"\t"+com2)
print("Work\t\tAM\t"+CO2workam+"\t"+com3)
print()
print("Work\t\tPM\t"+CO2workpm,"\t"+com4)
print("Transport\tPM\t"+CO2portpm+"\t"+ com5)
print("Home\t\tPM\t"+ CO2workpm+"\t"+com6)
 
